kind: pipeline
name : Finix Gcc Compiler
version: rev1.5_template
steps:
 - name: Building started..
   image: xyzuan/xdocker:latest
   environment:
     GITHUB_EMAIL:
       from_secret: EMAIL
     GITHUB_TOKEN:
       from_secret: API_TOKEN_GITHUB
     GITHUB_USER:
       from_secret: USERNAME
     BOT_TOKEN:
       from_secret: TELEGRAM_BOT_TOKEN
     CHAT_ID:
       from_secret: CHAT
     DRONE_USER_CREATE: AnGgIt88:octocat,admin:true
   commands:
     - export TZ=Asia/Jakarta
     - apt-get -y update && apt-get -y upgrade
     - apt-get install -y flex bison ncurses-dev texinfo gcc gperf patch libtool automake g++ libncurses5-dev gawk subversion expat libexpat1-dev python-all-dev binutils-dev bc libcap-dev autoconf libgmp-dev build-essential pkg-config libmpc-dev libmpfr-dev autopoint gettext txt2man liblzma-dev libssl-dev libz-dev mercurial wget tar gcc-10 g++-10 cmake zstd ninja-build lz4 liblz4-tool liblz4-dev lzma --fix-broken --fix-missing
     - alias gcc=gcc-10
     - alias g++=g++-10
     - git config --global user.name "${GITHUB_USER}"
     - git config --global user.email "${GITHUB_EMAIL}"
     - git clone https://"${GITHUB_USER}":"${GITHUB_TOKEN}"@github.com/"${GITHUB_USER}"/gcc-arm ../gcc-arm -b gcc-master
     - rm -rf ../gcc-arm/*
     - chmod a+x build-*.sh
     - curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" -d chat_id="${CHAT_ID}" -d "disable_web_page_preview=true" -d "parse_mode=html" -d text="<b>Starting ARM (32-bit) GCC Build</b>"
     - ./build-gcc.sh -a arm
     - sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
     - ./build-lld.sh -a arm
     - cd ../gcc-arm
     - ./bin/arm-eabi-gcc -v 2>&1 | tee /tmp/gcc-arm-version
     - ./bin/arm-eabi-ld.lld -v 2>&1 | tee /tmp/lld-arm-version
     - git add . -f
     - git commit -as -m "Import ARM GCC $(/bin/date)"  -m "Build completed on: $(/bin/date)" -m "Configuration: $(/bin/cat /tmp/gcc-arm-version)" -m "LLD: $(/bin/cat /tmp/lld-arm-version)"
     - git gc
     - git push origin gcc-master -f
