kind: pipeline
name : Finix Gcc Compiler
version: rev1.5_template
steps:
 - name: Building started..
   image: xyzuan/xdocker:latest
   environment:
     GITHUB_EMAIL:
       from_secret: EMAIL
     GITHUB_TOKEN:
       from_secret: API_TOKEN_GITHUB
     GITHUB_USER:
       from_secret: USERNAME
     BOT_TOKEN:
       from_secret: TELEGRAM_BOT_TOKEN
     CHAT_ID:
       from_secret: CHAT
     DRONE_USER_CREATE: AnGgIt88:octocat,admin:true
   commands:
     - export TZ=Asia/Jakarta
     - apt-get -y update && apt-get -y upgrade
     - apt-get install -y flex bison ncurses-dev texinfo gcc gperf patch libtool automake g++ libncurses5-dev gawk subversion expat libexpat1-dev python-all-dev binutils-dev bc libcap-dev autoconf libgmp-dev build-essential pkg-config libmpc-dev libmpfr-dev autopoint gettext txt2man liblzma-dev libssl-dev libz-dev mercurial wget tar gcc-10 g++-10 cmake zstd ninja-build lz4 liblz4-tool liblz4-dev lzma --fix-broken --fix-missing
     - gcc --version
